using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DDDSample.Domain.Cargo
{
   /// <summary>
   /// Uniquely identifies a particular cargo. Automatically generated by the application.
   /// </summary>
   [Serializable]
#pragma warning disable 661,660 //Equals and GetHashCode are overridden in ValueObject class.
   public class TrackingId : ValueObject
#pragma warning restore 661,660
   {
      /// <summary>
      /// Creates new <see cref="TrackingId"/> instacnce.
      /// </summary>
      /// <param name="idString">String representation of this new tracking id.</param>
      public TrackingId(string idString)
      {
         IdString = idString;
      }

      /// <summary>
      /// Returns string representation of this tracking id.
      /// </summary>
      public virtual string IdString { get; private set; }

      protected override IEnumerable<object> GetAtomicValues()
      {
         yield return IdString;
      }

      public static bool operator == (TrackingId left, TrackingId right)
      {
         return EqualOperator(left, right);
      }

      public static bool operator !=(TrackingId left, TrackingId right)
      {
         return NotEqualOperator(left, right);
      }

      /// <summary>
      /// For NHibernate.
      /// </summary>
      protected TrackingId()
      {         
      }
   }
}
