//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime OriginalVersion:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed.
        /// </summary>
        internal static string cargo_status_CLAIMED {
            get {
                return ResourceManager.GetString("cargo_status_CLAIMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In port {0}.
        /// </summary>
        internal static string cargo_status_IN_PORT {
            get {
                return ResourceManager.GetString("cargo_status_IN_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not received.
        /// </summary>
        internal static string cargo_status_NOT_RECEIVED {
            get {
                return ResourceManager.GetString("cargo_status_NOT_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboard voyage {0}.
        /// </summary>
        internal static string cargo_status_ONBOARD_CARRIER {
            get {
                return ResourceManager.GetString("cargo_status_ONBOARD_CARRIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string cargo_status_UNKNOWN {
            get {
                return ResourceManager.GetString("cargo_status_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimed in {0}, at {1}..
        /// </summary>
        internal static string eventDescription_CLAIM {
            get {
                return ResourceManager.GetString("eventDescription_CLAIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared customs in {0}, at {1}..
        /// </summary>
        internal static string eventDescription_CUSTOMS {
            get {
                return ResourceManager.GetString("eventDescription_CUSTOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded onto voyage {0} in {1}, at {2}..
        /// </summary>
        internal static string eventDescription_LOAD {
            get {
                return ResourceManager.GetString("eventDescription_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo has not yet been received..
        /// </summary>
        internal static string eventDescription_NOT_RECEIVED {
            get {
                return ResourceManager.GetString("eventDescription_NOT_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received in {0}, at {1}..
        /// </summary>
        internal static string eventDescription_RECEIVE {
            get {
                return ResourceManager.GetString("eventDescription_RECEIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded off voyage {0} in {1}, at {2}..
        /// </summary>
        internal static string eventDescription_UNLOAD {
            get {
                return ResourceManager.GetString("eventDescription_UNLOAD", resourceCulture);
            }
        }
    }
}
